import type { InterviewRole, Question } from '@/lib/types';

// Source: All_Questions_list/LD_Brain_NanduBhai_SelfFillForm.pdf (v3)
// 50 questions across 8 sections + 1 closing reflection. Designed for
// Nandu to fill at his own pace — 8 sessions of 15-20 min each.
//
// All MCQs are 'checkbox' (multi-select) per Nandu's preference: factory
// reality is rarely "exactly one of A/B/C/D" — he can tick everything that
// applies and add free-text notes in the "अन्य / Notes" textarea.
const nandu: Question[] = [
  // ─────────────────────────────────────────────
  // भाग 1 — दैनिक कामकाज (Daily Work)
  // ─────────────────────────────────────────────
  {
    id: 'Q1',
    section: 'Sec 1: Daily Work',
    sectionHi: 'भाग 1: दैनिक कामकाज',
    prompt: 'Subah factory aane ke baad aap sabse pehle kya karte hain?',
    promptHi: 'सुबह factory आने के बाद आप सबसे पहले क्या करते हैं?',
    type: 'checkbox',
    options: [
      'A. Machine warm-up check (printhead nozzle test)',
      'B. Pichle din ke pending orders dekhna',
      'C. Us din ka production schedule dekhna',
      'D. Staff ki haazri aur shift assignment',
    ],
    optionsHi: [
      'A. Machine warm-up check (printhead nozzle test)',
      'B. पिछले दिन के pending orders देखना',
      'C. उस दिन का production schedule देखना',
      'D. Staff की हाजरी और shift assignment',
    ],
    allowNotes: true,
  },
  {
    id: 'Q2',
    section: 'Sec 1: Daily Work',
    sectionHi: 'भाग 1: दैनिक कामकाज',
    prompt: 'Koi morning checklist jo aap mann mein follow karte hain — jo kahin likhi nahi hai?',
    promptHi: 'क्या आपकी कोई morning checklist है जो आप मन में follow करते हैं — जो कहीं लिखी नहीं है?',
    type: 'textarea',
  },
  {
    id: 'Q3',
    section: 'Sec 1: Daily Work',
    sectionHi: 'भाग 1: दैनिक कामकाज',
    prompt: 'Ek job complete hone ke baad kaun-kaun se steps hote hain? (Sab par tick karein)',
    promptHi: 'एक job complete होने के बाद कौन-कौन से steps होते हैं? (सब पर tick करें)',
    type: 'checkbox',
    options: [
      'A. Challan se fabric receive + meter count verify',
      'B. Design file ki setup — width alignment (36 / 58 / 64 / 72")',
      'C. Korean paper chunna (width + GSM)',
      'D. Printing machine par job chalana',
      'E. Fusing machine mein transfer (mandatory)',
      'F. Calendering (optional)',
      'G. KATA — roll-by-roll measurement + visual inspection',
      'H. KATA Certificate dena',
    ],
    optionsHi: [
      'A. Challan से fabric receive + meter count verify',
      'B. Design file की setup — width alignment (36 / 58 / 64 / 72")',
      'C. Korean paper चुनना (width + GSM)',
      'D. Printing machine पर job चलाना',
      'E. Fusing machine में transfer (ज़रूरी / mandatory)',
      'F. Calendering (optional)',
      'G. KATA — roll-by-roll measurement + visual inspection',
      'H. KATA Certificate देना',
    ],
    allowNotes: true,
  },
  {
    id: 'Q4',
    section: 'Sec 1: Daily Work',
    sectionHi: 'भाग 1: दैनिक कामकाज',
    prompt: 'Ek normal order — fabric receive se dispatch tak — kitna samay lagta hai?',
    promptHi: 'एक normal order — fabric receive से dispatch तक — कितना समय लगता है?',
    type: 'checkbox',
    options: [
      'A. Usi din (urgent jobs ke liye)',
      'B. 1-2 din',
      'C. 3-4 din',
      'D. 5-7 din',
    ],
    optionsHi: [
      'A. उसी दिन (urgent jobs के लिए)',
      'B. 1-2 दिन',
      'C. 3-4 दिन',
      'D. 5-7 दिन',
    ],
    allowNotes: true,
  },
  {
    id: 'Q5',
    section: 'Sec 1: Daily Work',
    sectionHi: 'भाग 1: दैनिक कामकाज',
    prompt: 'Order mein delay hone ke mukhya kaaran kya hain? (Sab par tick karein)',
    promptHi: 'Order में delay होने के मुख्य कारण क्या हैं? (सब पर tick करें)',
    type: 'checkbox',
    options: [
      'A. Fabric quality mein dikkat (polyester % kam hona)',
      'B. Design file galat ya adhoori aana',
      'C. Korean paper ka size match nahi karna',
      'D. Delta-E colour drift — production hold',
      'E. Fusing machine ki maintenance',
      'F. KATA mein shortage nikalna',
      'G. Customer se sample approval der se aana',
    ],
    optionsHi: [
      'A. Fabric quality में दिक्कत (polyester % कम होना)',
      'B. Design file गलत या अधूरी आना',
      'C. Korean paper का size match नहीं करना',
      'D. Delta-E colour drift — production hold',
      'E. Fusing machine की maintenance',
      'F. KATA में shortage निकलना',
      'G. Customer से sample approval देर से आना',
    ],
    allowNotes: true,
  },
  {
    id: 'Q6',
    section: 'Sec 1: Daily Work',
    sectionHi: 'भाग 1: दैनिक कामकाज',
    prompt: 'Quality hold kab karte hain? (Sab par tick karein)',
    promptHi: 'Quality hold कब करते हैं? (सब पर tick करें)',
    type: 'checkbox',
    options: [
      'A. Delta-E value 5 se upar jaaye',
      'B. Banding dikhe (horizontal dhariyaan)',
      'C. Ghosting dikhe (double image — fabric shift)',
      'D. Colour drift — ek roll se doosre roll mein farq',
      'E. Fading edges (uneven press pressure)',
      'F. Print ki sharpness kam lage (DPI / temperature ki dikkat)',
    ],
    optionsHi: [
      'A. Delta-E value 5 से ऊपर जाए',
      'B. Banding दिखे (horizontal धारियाँ)',
      'C. Ghosting दिखे (double image — fabric shift)',
      'D. Colour drift — एक roll से दूसरे roll में फर्क',
      'E. Fading edges (uneven press pressure)',
      'F. Print की sharpness कम लगे (DPI / temperature की दिक्कत)',
    ],
    allowNotes: true,
  },
  {
    id: 'Q7',
    section: 'Sec 1: Daily Work',
    sectionHi: 'भाग 1: दैनिक कामकाज',
    prompt: 'Quality check ka koi tareeka hai jo aap mann mein karte hain — jo kahin likha nahi hai?',
    promptHi: 'Quality check का कोई तरीका है जो आप मन में करते हैं — जो कहीं लिखा नहीं है?',
    type: 'textarea',
  },

  // ─────────────────────────────────────────────
  // भाग 2 — मशीन और रखरखाव (Machines and Maintenance)
  // ─────────────────────────────────────────────
  {
    id: 'Q8',
    section: 'Sec 2: Machines and Maintenance',
    sectionHi: 'भाग 2: मशीन और रखरखाव',
    prompt: 'Humare paas abhi kaun-kaun si chalu (active) printing machines hain? (Sab par tick karein)',
    promptHi: 'हमारे पास अभी कौन-कौन सी चालू (active) printing machines हैं? (सब पर tick करें)',
    type: 'checkbox',
    options: [
      'A. PANTONE L1916 (16-head) Machine 1',
      'B. PANTONE L1916 (16-head) Machine 2',
      'C. PANTONE L1912 (12-head) Machine',
      'D. PANTONE XENON (8-head) Unit 1',
      'E. PANTONE XENON (8-head) Unit 2',
    ],
    optionsHi: [
      'A. PANTONE L1916 (16-head) Machine 1',
      'B. PANTONE L1916 (16-head) Machine 2',
      'C. PANTONE L1912 (12-head) Machine',
      'D. PANTONE XENON (8-head) Unit 1',
      'E. PANTONE XENON (8-head) Unit 2',
    ],
    allowNotes: true,
  },
  {
    id: 'Q9',
    section: 'Sec 2: Machines and Maintenance',
    sectionHi: 'भाग 2: मशीन और रखरखाव',
    prompt: '5 idle machines (3-head, puraani) — kab chalu karni chahiye? Kis situation mein?',
    promptHi: '5 idle machines (3-head, पुरानी) — कब चालू करनी चाहिए? किस situation में?',
    type: 'textarea',
  },
  {
    id: 'Q10',
    section: 'Sec 2: Machines and Maintenance',
    sectionHi: 'भाग 2: मशीन और रखरखाव',
    prompt: 'Daily machine maintenance mein kya-kya hota hai? (Sab par tick karein)',
    promptHi: 'Daily machine maintenance में क्या-क्या होता है? (सब पर tick करें)',
    type: 'checkbox',
    options: [
      'A. Printhead nozzle test print',
      'B. Ink system flush (colour change par)',
      'C. Paper feed tension check',
      'D. Printhead height adjust (fabric ki motai ke hisaab se)',
      'E. Temperature aur speed ki calibration verify',
      'F. Belt aur roller ko saaf karna',
    ],
    optionsHi: [
      'A. Printhead nozzle test print',
      'B. Ink system flush (colour change पर)',
      'C. Paper feed tension check',
      'D. Printhead height adjust (fabric की मोटाई के हिसाब से)',
      'E. Temperature और speed की calibration verify',
      'F. Belt और roller को साफ करना',
    ],
    allowNotes: true,
  },
  {
    id: 'Q11',
    section: 'Sec 2: Machines and Maintenance',
    sectionHi: 'भाग 2: मशीन और रखरखाव',
    prompt: 'Printhead repair ya badalne ka samay kab aata hai? Kaun se signs dekhkar pata chalta hai?',
    promptHi: 'Printhead repair या बदलने का समय कब आता है? कौन से signs देखकर पता चलता है?',
    type: 'textarea',
  },
  {
    id: 'Q12',
    section: 'Sec 2: Machines and Maintenance',
    sectionHi: 'भाग 2: मशीन और रखरखाव',
    prompt: 'Fusing machine FM-01 ya FM-02 — kaun sa job kis machine par jaata hai?',
    promptHi: 'Fusing machine FM-01 या FM-02 — कौन सा job किस machine पर जाता है?',
    type: 'checkbox',
    options: [
      'A. FM-02 (14,000 meter/din) — bade orders ke liye',
      'B. FM-01 (5,000 meter/din) — chhote ya urgent jobs ke liye',
      'C. Jo machine us samay khali ho use use karte hain',
      'D. Koi pakka niyam nahi',
    ],
    optionsHi: [
      'A. FM-02 (14,000 मीटर/दिन) — बड़े orders के लिए',
      'B. FM-01 (5,000 मीटर/दिन) — छोटे या urgent jobs के लिए',
      'C. जो machine उस समय खाली हो उसे use करते हैं',
      'D. कोई पक्का नियम नहीं',
    ],
    allowNotes: true,
  },
  {
    id: 'Q13',
    section: 'Sec 2: Machines and Maintenance',
    sectionHi: 'भाग 2: मशीन और रखरखाव',
    prompt: 'Fusing temperature aur speed — fabric type ke hisaab se kaise set karte hain? (185-230°C ke beech — aap actually kya rakhte hain)',
    promptHi: 'Fusing temperature और speed — fabric type के हिसाब से कैसे set करते हैं? (185–230°C के बीच — आप actually क्या रखते हैं)',
    type: 'textarea',
    help: 'Har fabric ke liye likhein — Nokia 58" / Satin Slub / Heavy (Scuba, Blackout) / Light (Georgette) / Waffle Lycra / Blackout 54 / Doosra. Format: Fabric — Temp (°C) — Speed (m/hr) — Notes',
  },
  {
    id: 'Q14',
    section: 'Sec 2: Machines and Maintenance',
    sectionHi: 'भाग 2: मशीन और रखरखाव',
    prompt: 'Aise spare parts jo hamesha stock mein rakhne chahiye? (Sab par tick karein)',
    promptHi: 'ऐसे spare parts जो हमेशा stock में रखने चाहिए? (सब पर tick करें)',
    type: 'checkbox',
    options: [
      'A. Printhead (PANTONE ke compatible)',
      'B. Ink pump aur tubing (printing machine ke)',
      'C. Heating elements (fusing machine ke)',
      'D. Paper core holders',
      'E. Electrical fuses aur circuit parts',
      'F. Belt / rollers (calendar aur fusing ke)',
    ],
    optionsHi: [
      'A. Printhead (PANTONE के compatible)',
      'B. Ink pump और tubing (printing machine के)',
      'C. Heating elements (fusing machine के)',
      'D. Paper core holders',
      'E. Electrical fuses और circuit parts',
      'F. Belt / rollers (calendar और fusing के)',
    ],
    allowNotes: true,
  },
  {
    id: 'Q15',
    section: 'Sec 2: Machines and Maintenance',
    sectionHi: 'भाग 2: मशीन और रखरखाव',
    prompt: 'PANTONE machine ke parts kahan se milte hain? Supplier ka naam aur number?',
    promptHi: 'PANTONE machine के parts कहाँ से मिलते हैं? Supplier का नाम और number?',
    type: 'textarea',
    help: 'Supplier ka naam · Contact person · Phone/WhatsApp · Lead time (order se delivery) · Notes',
  },
  {
    id: 'Q16',
    section: 'Sec 2: Machines and Maintenance',
    sectionHi: 'भाग 2: मशीन और रखरखाव',
    prompt: 'MDO ko machine kaise assign karte hain?',
    promptHi: 'MDO को machine कैसे assign करते हैं?',
    type: 'checkbox',
    options: [
      'A. Har MDO ki ek fixed machine hoti hai',
      'B. Jo available ho use jahan zaroorat ho wahan lagate hain',
      'C. MDO ki training aur certification dekhkar',
      'D. Job ki difficulty dekhkar',
    ],
    optionsHi: [
      'A. हर MDO की एक fixed machine होती है',
      'B. जो available हो उसे जहाँ ज़रूरत हो वहाँ लगाते हैं',
      'C. MDO की training और certification देखकर',
      'D. Job की difficulty देखकर',
    ],
    allowNotes: true,
  },

  // ─────────────────────────────────────────────
  // भाग 3 — Fusing और Defects की पहचान (Fusing and Defects)
  // ─────────────────────────────────────────────
  {
    id: 'Q17',
    section: 'Sec 3: Fusing and Defects',
    sectionHi: 'भाग 3: Fusing और Defects की पहचान',
    prompt: 'Nokia 58" ke liye fusing temperature kitna rakhte hain?',
    promptHi: 'Nokia 58" के लिए fusing temperature कितना रखते हैं?',
    type: 'checkbox',
    options: [
      'A. 185-190°C',
      'B. 195-205°C',
      'C. 210-220°C',
      'D. 225-230°C',
    ],
    optionsHi: [
      'A. 185–190°C',
      'B. 195–205°C',
      'C. 210–220°C',
      'D. 225–230°C',
    ],
    allowNotes: true,
    help: 'Exact value Notes mein likh sakte hain',
  },
  {
    id: 'Q18',
    section: 'Sec 3: Fusing and Defects',
    sectionHi: 'भाग 3: Fusing और Defects की पहचान',
    prompt: 'Satin Slub ke liye Nokia 58" se compare karein to temperature?',
    promptHi: 'Satin Slub के लिए Nokia 58" से compare करें तो temperature?',
    type: 'checkbox',
    options: [
      'A. Nokia se zyada rakhte hain — Satin bhaari (heavy) hai',
      'B. Nokia se kam rakhte hain — Satin naazuk (delicate) hai',
      'C. Ek jaisa (same) temperature rakhte hain',
      'D. Temperature same rakhte hain lekin speed kam kar dete hain',
    ],
    optionsHi: [
      'A. Nokia से ज़्यादा रखते हैं — Satin भारी (heavy) है',
      'B. Nokia से कम रखते हैं — Satin नाज़ुक (delicate) है',
      'C. एक जैसा (same) temperature रखते हैं',
      'D. Temperature same रखते हैं लेकिन speed कम कर देते हैं',
    ],
    allowNotes: true,
  },
  {
    id: 'Q19',
    section: 'Sec 3: Fusing and Defects',
    sectionHi: 'भाग 3: Fusing और Defects की पहचान',
    prompt: 'Heavy fabric (Scuba, Blackout, moti Georgette) par temperature?',
    promptHi: 'Heavy fabric (Scuba, Blackout, मोटी Georgette) पर temperature?',
    type: 'checkbox',
    options: [
      'A. Standard se 10-15°C zyada',
      'B. Standard se 20-25°C zyada',
      'C. Temperature same, speed kam',
      'D. Pehle chhota test karte hain, fir adjust',
    ],
    optionsHi: [
      'A. Standard से 10–15°C ज़्यादा',
      'B. Standard से 20–25°C ज़्यादा',
      'C. Temperature same, speed कम',
      'D. पहले छोटा test करते हैं, फिर adjust',
    ],
    allowNotes: true,
  },
  {
    id: 'Q20',
    section: 'Sec 3: Fusing and Defects',
    sectionHi: 'भाग 3: Fusing और Defects की पहचान',
    prompt: 'Under-fused fabric (kam fuse hua) kaise pehchante hain?',
    promptHi: 'Under-fused fabric (कम fuse हुआ) कैसे पहचानते हैं?',
    type: 'checkbox',
    options: [
      'A. Rang feeka dikhta hai, theek se transfer nahi hua',
      'B. Haath se ragadne par rang nikalta hai',
      'C. Surface par design dhundhla dikhta hai',
      'D. Kinaron par design kam, beech mein theek',
    ],
    optionsHi: [
      'A. रंग फीका दिखता है, ठीक से transfer नहीं हुआ',
      'B. हाथ से रगड़ने पर रंग निकलता है',
      'C. Surface पर design धुंधला दिखता है',
      'D. किनारों पर design कम, बीच में ठीक',
    ],
    allowNotes: true,
  },
  {
    id: 'Q21',
    section: 'Sec 3: Fusing and Defects',
    sectionHi: 'भाग 3: Fusing और Defects की पहचान',
    prompt: 'Over-fused fabric (zyada fuse hua) kaise pehchante hain?',
    promptHi: 'Over-fused fabric (ज़्यादा fuse हुआ) कैसे पहचानते हैं?',
    type: 'checkbox',
    options: [
      'A. Fabric sakht (stiff) ho jati hai, haath mein kada lagta hai',
      'B. Rang bahut gehre aate hain, original se dark',
      'C. Fabric ki chamak (shine) badal jaati hai',
      'D. Edges burn ho jate hain ya darken hote hain',
    ],
    optionsHi: [
      'A. Fabric सख्त (stiff) हो जाती है, हाथ में कड़ा लगता है',
      'B. रंग बहुत गहरे आते हैं, original से dark',
      'C. Fabric की चमक (shine) बदल जाती है',
      'D. Edges burn हो जाते हैं या darken होते हैं',
    ],
    allowNotes: true,
  },
  {
    id: 'Q22',
    section: 'Sec 3: Fusing and Defects',
    sectionHi: 'भाग 3: Fusing और Defects की पहचान',
    prompt: 'Banding (horizontal dhariyaan) aane par sabse pehle kya karte hain?',
    promptHi: 'Banding (horizontal धारियाँ) आने पर सबसे पहले क्या करते हैं?',
    type: 'checkbox',
    options: [
      'A. Nozzle check print — printhead ko check karte hain',
      'B. Paper badalte hain',
      'C. Machine band karke fir se restart',
      'D. Printhead cleaning cycle chalate hain',
    ],
    optionsHi: [
      'A. Nozzle check print — printhead को चेक करते हैं',
      'B. Paper बदलते हैं',
      'C. Machine बंद करके फिर से restart',
      'D. Printhead cleaning cycle चलाते हैं',
    ],
    allowNotes: true,
  },
  {
    id: 'Q23',
    section: 'Sec 3: Fusing and Defects',
    sectionHi: 'भाग 3: Fusing और Defects की पहचान',
    prompt: 'Ghosting (double image) ka sabse aam kaaran kya hai?',
    promptHi: 'Ghosting (double image) का सबसे आम कारण क्या है?',
    type: 'checkbox',
    options: [
      'A. Fabric machine mein hil jaati hai — movement',
      'B. Temperature bahut zyada — fabric slip kar jaati hai',
      'C. Paper aur fabric theek se align nahi the',
      'D. Speed bahut tez thi',
    ],
    optionsHi: [
      'A. Fabric machine में हिल जाती है — movement',
      'B. Temperature बहुत ज़्यादा — fabric slip कर जाती है',
      'C. Paper और fabric ठीक से align नहीं थे',
      'D. Speed बहुत तेज़ थी',
    ],
    allowNotes: true,
  },

  // ─────────────────────────────────────────────
  // भाग 4 — Paper और Ink
  // ─────────────────────────────────────────────
  {
    id: 'Q24',
    section: 'Sec 4: Paper and Ink',
    sectionHi: 'भाग 4: Paper और Ink',
    prompt: 'Korean paper ka width kaise decide karte hain order ke liye?',
    promptHi: 'Korean paper का width कैसे decide करते हैं order के लिए?',
    type: 'checkbox',
    options: [
      'A. Customer ki fabric width ke hisaab se (36 / 63 / 64 / 72")',
      'B. Jo stock mein ho wahi use karte hain',
      'C. Hamesha ek hi standard width',
      'D. Machine ki printing width ke hisaab se',
    ],
    optionsHi: [
      'A. Customer की fabric width के हिसाब से (36 / 63 / 64 / 72")',
      'B. जो stock में हो वही use करते हैं',
      'C. हमेशा एक ही standard width',
      'D. Machine की printing width के हिसाब से',
    ],
    allowNotes: true,
  },
  {
    id: 'Q25',
    section: 'Sec 4: Paper and Ink',
    sectionHi: 'भाग 4: Paper और Ink',
    prompt: '38 GSM aur 45 GSM paper — kab kiska use karte hain? Result mein kya farq padta hai?',
    promptHi: '38 GSM और 45 GSM paper — कब किसका use करते हैं? Result में क्या फर्क पड़ता है?',
    type: 'textarea',
  },
  {
    id: 'Q26',
    section: 'Sec 4: Paper and Ink',
    sectionHi: 'भाग 4: Paper और Ink',
    prompt: 'Korean paper ka stock kitne din ka rakhte hain?',
    promptHi: 'Korean paper का stock कितने दिन का रखते हैं?',
    type: 'checkbox',
    options: [
      'A. 7-10 din',
      'B. 15-20 din',
      'C. 1 mahina',
      'D. 2 mahine ya zyada',
    ],
    optionsHi: [
      'A. 7-10 दिन',
      'B. 15-20 दिन',
      'C. 1 महीना',
      'D. 2 महीने या ज़्यादा',
    ],
    allowNotes: true,
  },
  {
    id: 'Q27',
    section: 'Sec 4: Paper and Ink',
    sectionHi: 'भाग 4: Paper और Ink',
    prompt: 'Paper storage kahan aur kaise karte hain? Temperature aur humidity ka khayal rakhte hain?',
    promptHi: 'Paper storage कहाँ और कैसे करते हैं? Temperature और humidity का ख़याल रखते हैं?',
    type: 'textarea',
  },
  {
    id: 'Q28',
    section: 'Sec 4: Paper and Ink',
    sectionHi: 'भाग 4: Paper और Ink',
    prompt: 'Humidity mein rakha paper roll kaise pehchante hain kharab ho gaya hai?',
    promptHi: 'Humidity में रखा paper roll कैसे पहचानते हैं कि ख़राब हो गया है?',
    type: 'checkbox',
    options: [
      'A. Paper ki edge curl ho jaati hai',
      'B. Print karne par colour bleed hota hai',
      'C. Paper machine mein wrinkle (mudta) pad jata hai',
      'D. Haath lagane par soft ya nam (damp) lagta hai',
    ],
    optionsHi: [
      'A. Paper की edge curl हो जाती है',
      'B. Print करने पर colour bleed होता है',
      'C. Paper machine में wrinkle (मुड़ता) पड़ जाता है',
      'D. हाथ लगाने पर soft या नम (damp) लगता है',
    ],
    allowNotes: true,
  },
  {
    id: 'Q29',
    section: 'Sec 4: Paper and Ink',
    sectionHi: 'भाग 4: Paper और Ink',
    prompt: 'PANTONE Royal Splash ink ke baare mein kya-kya check karte hain? (Sab par tick karein)',
    promptHi: 'PANTONE Royal Splash ink के बारे में क्या-क्या check करते हैं? (सब पर tick करें)',
    type: 'checkbox',
    options: [
      'A. Ink expiry date (12 month shelf life)',
      'B. Storage temperature (15-25°C)',
      'C. Naye ink batch par test print',
      'D. CMYK balance check',
      'E. Ink level alerts',
    ],
    optionsHi: [
      'A. Ink expiry date (12 month shelf life)',
      'B. Storage temperature (15–25°C)',
      'C. नए ink batch पर test print',
      'D. CMYK balance check',
      'E. Ink level alerts',
    ],
    allowNotes: true,
  },
  {
    id: 'Q30',
    section: 'Sec 4: Paper and Ink',
    sectionHi: 'भाग 4: Paper और Ink',
    prompt: 'Ink supplier ka naam, contact aur mahine ka approximate quantity?',
    promptHi: 'Ink supplier का नाम, contact और महीने का approximate quantity?',
    type: 'textarea',
    help: 'Supplier ka naam · Contact person · Phone/WhatsApp · Monthly quantity (litres) · Lead time',
  },

  // ─────────────────────────────────────────────
  // भाग 5 — Order, Quality और KATA
  // ─────────────────────────────────────────────
  {
    id: 'Q31',
    section: 'Sec 5: Order, Quality and KATA',
    sectionHi: 'भाग 5: Order, Quality और KATA',
    prompt: 'Naya order accept karne se pehle kya-kya check karte hain? (Sab par tick karein)',
    promptHi: 'नया order accept करने से पहले क्या-क्या check करते हैं? (सब पर tick करें)',
    type: 'checkbox',
    options: [
      'A. Fabric ki polyester % confirm (50%+ zaroori)',
      'B. Machine ki available capacity',
      'C. Korean paper available hai ya nahi',
      'D. Sample approval hua hai (naye customer ke liye)',
      'E. Delivery date possible hai ya nahi',
    ],
    optionsHi: [
      'A. Fabric की polyester % confirm (50%+ ज़रूरी)',
      'B. Machine की available capacity',
      'C. Korean paper available है या नहीं',
      'D. Sample approval हुआ है (नए customer के लिए)',
      'E. Delivery date possible है या नहीं',
    ],
    allowNotes: true,
  },
  {
    id: 'Q32',
    section: 'Sec 5: Order, Quality and KATA',
    sectionHi: 'भाग 5: Order, Quality और KATA',
    prompt: 'Sample approval mein aapka role hota hai? Final approval kaun karta hai?',
    promptHi: 'Sample approval में आपका role होता है? Final approval कौन करता है?',
    type: 'textarea',
  },
  {
    id: 'Q33',
    section: 'Sec 5: Order, Quality and KATA',
    sectionHi: 'भाग 5: Order, Quality और KATA',
    prompt: 'KATA process mein exactly kya-kya hota hai? (Sab par tick karein)',
    promptHi: 'KATA process में exactly क्या-क्या होता है? (सब पर tick करें)',
    type: 'checkbox',
    options: [
      'A. Roll-by-roll meter measurement (±0.5%)',
      'B. Har roll ki visual inspection',
      'C. Defect marking (DEF code + photo)',
      'D. Final meter count banaam order compare',
      'E. Shortage hone par customer ko notify',
      'F. KATA Certificate dena (KAT-YYYY-MM-NNNN)',
    ],
    optionsHi: [
      'A. Roll-by-roll meter measurement (±0.5%)',
      'B. हर roll की visual inspection',
      'C. Defect marking (DEF code + photo)',
      'D. Final meter count बनाम order compare',
      'E. Shortage होने पर customer को notify',
      'F. KATA Certificate देना (KAT-YYYY-MM-NNNN)',
    ],
    allowNotes: true,
  },
  {
    id: 'Q34',
    section: 'Sec 5: Order, Quality and KATA',
    sectionHi: 'भाग 5: Order, Quality और KATA',
    prompt: 'KATA mein common rejection ya shortage ke kaaran kya hain?',
    promptHi: 'KATA में common rejection या shortage के कारण क्या हैं?',
    type: 'textarea',
  },
  {
    id: 'Q35',
    section: 'Sec 5: Order, Quality and KATA',
    sectionHi: 'भाग 5: Order, Quality और KATA',
    prompt: 'Kitna colour difference acceptable hai? (Delta-E)',
    promptHi: 'कितना colour difference acceptable है? (Delta-E)',
    type: 'checkbox',
    options: [
      'A. Bilkul match hona chahiye — 0 se 2',
      'B. Thoda farq chalta hai — 0 se 3',
      'C. Practical tolerance — 0 se 5',
      'D. Customer ke hisaab se — dekhkar tay karte hain',
    ],
    optionsHi: [
      'A. बिल्कुल match होना चाहिए — 0 से 2',
      'B. थोड़ा फर्क चलता है — 0 से 3',
      'C. Practical tolerance — 0 से 5',
      'D. Customer के हिसाब से — देखकर तय करते हैं',
    ],
    allowNotes: true,
  },
  {
    id: 'Q36',
    section: 'Sec 5: Order, Quality and KATA',
    sectionHi: 'भाग 5: Order, Quality और KATA',
    prompt: 'Zyada orders hon to priority kaise decide karte hain?',
    promptHi: 'ज़्यादा orders हों तो priority कैसे decide करते हैं?',
    type: 'checkbox',
    options: [
      'A. Urgent delivery waale pehle',
      'B. Book A (LD Silk captive) ko hamesha priority',
      'C. Bade order (zyada meter) pehle',
      'D. Jo order pehle aaya (FIFO)',
      'E. Raghav bhai se poochkar decide karte hain',
    ],
    optionsHi: [
      'A. Urgent delivery वाले पहले',
      'B. Book A (LD Silk captive) को हमेशा priority',
      'C. बड़े order (ज़्यादा मीटर) पहले',
      'D. जो order पहले आया (FIFO)',
      'E. राघव भाई से पूछकर decide करते हैं',
    ],
    allowNotes: true,
  },
  {
    id: 'Q37',
    section: 'Sec 5: Order, Quality and KATA',
    sectionHi: 'भाग 5: Order, Quality और KATA',
    prompt: 'Kabhi Book A aur Book B mein conflict hua ho? Kaise handle kiya?',
    promptHi: 'कभी Book A और Book B में conflict हुआ हो? कैसे handle किया?',
    type: 'textarea',
  },
  {
    id: 'Q38',
    section: 'Sec 5: Order, Quality and KATA',
    sectionHi: 'भाग 5: Order, Quality और KATA',
    prompt: 'Job 980 metres bani, lekin order 1000 metres ka tha — kya karte hain?',
    promptHi: 'Job 980 metres बनी, लेकिन order 1000 metres का था — क्या करते हैं?',
    type: 'checkbox',
    options: [
      'A. 980 dispatch kar dete hain, customer ko batakar balance baad mein',
      'B. Job rokte hain — 1000 poora hone tak rukte hain',
      'C. 20 metres reprint karke saath bhej dete hain',
      'D. Raghav bhai se poochte hain',
    ],
    optionsHi: [
      'A. 980 dispatch कर देते हैं, customer को बताकर balance बाद में',
      'B. Job रोकते हैं — 1000 पूरा होने तक रुकते हैं',
      'C. 20 metres reprint करके साथ भेज देते हैं',
      'D. राघव भाई से पूछते हैं',
    ],
    allowNotes: true,
  },

  // ─────────────────────────────────────────────
  // भाग 6 — Fabric Receiving
  // ─────────────────────────────────────────────
  {
    id: 'Q39',
    section: 'Sec 6: Fabric Receiving',
    sectionHi: 'भाग 6: Fabric Receiving',
    prompt: 'Customer ki fabric aane par metres kaise check karte hain?',
    promptHi: 'Customer की fabric आने पर metres कैसे check करते हैं?',
    type: 'checkbox',
    options: [
      'A. Roll ko manually counter par naapte hain — har baar',
      'B. Visual estimate se andaaza lagate hain',
      'C. Weight se calculate karte hain',
      'D. Customer ke challan par bharosa, sirf spot check',
    ],
    optionsHi: [
      'A. Roll को manually counter पर नापते हैं — हर बार',
      'B. Visual estimate से अंदाज़ा लगाते हैं',
      'C. Weight से calculate करते हैं',
      'D. Customer के challan पर भरोसा, सिर्फ spot check',
    ],
    allowNotes: true,
  },
  {
    id: 'Q40',
    section: 'Sec 6: Fabric Receiving',
    sectionHi: 'भाग 6: Fabric Receiving',
    prompt: 'Fabric customer ke challan se kam nikle to kya karte hain?',
    promptHi: 'Fabric customer के challan से कम निकले तो क्या करते हैं?',
    type: 'checkbox',
    options: [
      'A. Anand bhai ko batate hain — wo customer se baat karte hain',
      'B. Customer ko directly call/WhatsApp karte hain',
      'C. Discrepancy note banate hain aur job rokte hain customer confirm karne tak',
      'D. Kam meter ka job banakar aage badhte hain',
    ],
    optionsHi: [
      'A. आनंद भाई को बताते हैं — वो customer से बात करते हैं',
      'B. Customer को directly call/WhatsApp करते हैं',
      'C. Discrepancy note बनाते हैं और job रोकते हैं customer confirm करने तक',
      'D. कम मीटर का job बनाकर आगे बढ़ते हैं',
    ],
    allowNotes: true,
  },
  {
    id: 'Q41',
    section: 'Sec 6: Fabric Receiving',
    sectionHi: 'भाग 6: Fabric Receiving',
    prompt: 'Damaged fabric aaye to kya karte hain?',
    promptHi: 'Damaged fabric आए तो क्या करते हैं?',
    type: 'checkbox',
    options: [
      'A. Waapas bhej dete hain',
      'B. Photo lete hain, customer ko batakar unki permission se accept',
      'C. Damaged hissa mark karte hain, baaki par print karte hain',
      'D. Anand / Raghav bhai se poochte hain, wo decide karein',
    ],
    optionsHi: [
      'A. वापस भेज देते हैं',
      'B. Photo लेते हैं, customer को बताकर उनकी permission से accept',
      'C. Damaged हिस्सा mark करते हैं, बाकी पर print करते हैं',
      'D. आनंद / राघव भाई से पूछते हैं, वो decide करें',
    ],
    allowNotes: true,
  },
  {
    id: 'Q42',
    section: 'Sec 6: Fabric Receiving',
    sectionHi: 'भाग 6: Fabric Receiving',
    prompt: 'Fabric kitne din store mein rahe to customer ko remind karte hain ki order dein?',
    promptHi: 'Fabric कितने दिन store में रहे तो customer को remind करते हैं कि order दें?',
    type: 'checkbox',
    options: [
      'A. 15 din',
      'B. 30 din',
      'C. 45 din',
      'D. Jab tak customer order na de — hamari zimmedari',
    ],
    optionsHi: [
      'A. 15 दिन',
      'B. 30 दिन',
      'C. 45 दिन',
      'D. जब तक customer order न दे — हमारी ज़िम्मेदारी',
    ],
    allowNotes: true,
  },

  // ─────────────────────────────────────────────
  // भाग 7 — Dispatch और Packaging
  // ─────────────────────────────────────────────
  {
    id: 'Q43',
    section: 'Sec 7: Dispatch and Packaging',
    sectionHi: 'भाग 7: Dispatch और Packaging',
    prompt: 'Finished fabric roll ki packaging standard kya hai?',
    promptHi: 'Finished fabric roll की packaging standard क्या है?',
    type: 'checkbox',
    options: [
      'A. Polybag mein lapetkar, fir brown paper',
      'B. Sirf polybag — fabric ke upar',
      'C. Customer ke hisaab se alag-alag packaging',
      'D. Hard core mein roll karke polybag',
    ],
    optionsHi: [
      'A. Polybag में लपेटकर, फिर brown paper',
      'B. सिर्फ polybag — fabric के ऊपर',
      'C. Customer के हिसाब से अलग-अलग packaging',
      'D. Hard core में roll करके polybag',
    ],
    allowNotes: true,
  },
  {
    id: 'Q44',
    section: 'Sec 7: Dispatch and Packaging',
    sectionHi: 'भाग 7: Dispatch और Packaging',
    prompt: 'Roll label par kya-kya likhte hain?',
    promptHi: 'Roll label पर क्या-क्या लिखते हैं?',
    type: 'checkbox',
    options: [
      'A. Customer ka naam + Job number + metres',
      'B. Customer ka naam + design name + width + metres',
      'C. Challan number + roll number + metres',
      'D. Sab — customer, design, width, metres, challan number',
    ],
    optionsHi: [
      'A. Customer का नाम + Job number + metres',
      'B. Customer का नाम + design name + width + metres',
      'C. Challan number + roll number + metres',
      'D. सब — customer, design, width, metres, challan number',
    ],
    allowNotes: true,
  },

  // ─────────────────────────────────────────────
  // भाग 8 — Team और Training
  // ─────────────────────────────────────────────
  {
    id: 'Q45',
    section: 'Sec 8: Team and Training',
    sectionHi: 'भाग 8: Team और Training',
    prompt: 'Aapki team mein kitne log hain?',
    promptHi: 'आपकी team में कितने लोग हैं?',
    type: 'checkbox',
    options: [
      'A. 5 se kam',
      'B. 5-10 log',
      'C. 10-15 log',
      'D. 15 se zyada',
    ],
    optionsHi: [
      'A. 5 से कम',
      'B. 5-10 लोग',
      'C. 10-15 लोग',
      'D. 15 से ज़्यादा',
    ],
    allowNotes: true,
    help: 'Exact number Notes mein likh sakte hain',
  },
  {
    id: 'Q46',
    section: 'Sec 8: Team and Training',
    sectionHi: 'भाग 8: Team और Training',
    prompt: 'Har team member ka naam aur kaam? (MDO / QC / KATA / Dispatch / Packaging)',
    promptHi: 'हर team member का नाम और काम? (MDO / QC / KATA / Dispatch / Packaging)',
    type: 'textarea',
    help: 'Format: Naam — Role — Kitne saal se — Koi special skill',
  },
  {
    id: 'Q47',
    section: 'Sec 8: Team and Training',
    sectionHi: 'भाग 8: Team और Training',
    prompt: 'MDO (Machine/Design Operator) ko nayi machine par train karne mein kitna samay lagta hai?',
    promptHi: 'MDO (Machine/Design Operator) को नई machine पर train करने में कितना समय लगता है?',
    type: 'checkbox',
    options: [
      'A. 1 hafte se kam',
      'B. 2-4 hafte',
      'C. 1-2 mahine',
      'D. 3 mahine ya zyada',
    ],
    optionsHi: [
      'A. 1 हफ्ते से कम',
      'B. 2-4 हफ्ते',
      'C. 1-2 महीने',
      'D. 3 महीने या ज़्यादा',
    ],
    allowNotes: true,
  },
  {
    id: 'Q48',
    section: 'Sec 8: Team and Training',
    sectionHi: 'भाग 8: Team और Training',
    prompt: 'MDO ko kaise certify karte hain? Koi specific test ya checklist hoti hai?',
    promptHi: 'MDO को कैसे certify करते हैं? कोई specific test या checklist होती है?',
    type: 'textarea',
  },
  {
    id: 'Q49',
    section: 'Sec 8: Team and Training',
    sectionHi: 'भाग 8: Team और Training',
    prompt: 'Factory mein kaun se zaroori kaam hain jinhein AI tool mein automate hona chahiye? (Sab par tick karein)',
    promptHi: 'Factory में कौन से ज़रूरी काम हैं जिन्हें AI tool में automate होना चाहिए? (सब पर tick करें)',
    type: 'checkbox',
    options: [
      'A. PANTONE machine settings (priority aur speed) decide karna',
      'B. Korean paper GSM selection (job type ke hisaab se)',
      'C. Defect diagnosis aur production hold decision',
      'D. KATA final approval',
      'E. Sample approval ke baad production decision',
      'F. Shift staffing aur machine allocation',
      'G. Customer issue handling routing',
    ],
    optionsHi: [
      'A. PANTONE machine settings (priority और speed) decide करना',
      'B. Korean paper GSM selection (job type के हिसाब से)',
      'C. Defect diagnosis और production hold decision',
      'D. KATA final approval',
      'E. Sample approval के बाद production decision',
      'F. Shift staffing और machine allocation',
      'G. Customer issue handling routing',
    ],
    allowNotes: true,
  },
  {
    id: 'Q50',
    section: 'Sec 8: Team and Training',
    sectionHi: 'भाग 8: Team और Training',
    prompt: 'Emergency contacts — naam aur number (PANTONE technician, electrician, paper supplier, ink supplier, spare parts vendor, AMC / machine repair)',
    promptHi: 'Emergency contacts — नाम और number (PANTONE technician, electrician, paper supplier, ink supplier, spare parts vendor, AMC / machine repair)',
    type: 'textarea',
    help: 'Format: Service — Naam — Phone/WhatsApp — Notes (har service ke liye ek line)',
  },

  // ─────────────────────────────────────────────
  // Final reflection
  // ─────────────────────────────────────────────
  {
    id: 'Q51',
    section: 'Final',
    sectionHi: 'अंतिम प्रश्न',
    prompt: 'Aur kuch? Koi zaroori baat jo company mein sabko hamesha pata rehni chahiye? Koi tip, suggestion, ya factory ki baat jo aap share karna chahte hain?',
    promptHi: 'और कुछ? कोई ज़रूरी बात जो company में सबको हमेशा पता रहनी चाहिए? कोई tip, suggestion, या factory की बात जो आप share करना चाहते हैं?',
    type: 'textarea',
  },
];

const md: Question[] = [
  { id: 'M1', section: 'Management Vision', prompt: 'Aaj ke liye top 3 business priorities kya hain?', type: 'textarea' },
  { id: 'M2', section: 'Management Vision', prompt: 'Aap kis cheez par bilkul compromise nahi karna chahte?', type: 'textarea' },
  { id: 'M3', section: 'Decision Rules', prompt: 'Speed, quality, cost mein conflict aaye to decision rule kya hota hai?', type: 'radio', options: ['Speed first', 'Quality first', 'Cost first', 'Case by case'] },
  { id: 'M4', section: 'Growth', prompt: 'Agale 90 din mein sabse bada growth goal kya hai?', type: 'textarea' },
  { id: 'M5', section: 'Bottlenecks', prompt: 'Aaj growth ko sabse zyada kya block kar raha hai?', type: 'textarea' },
  { id: 'M6', section: 'Knowledge Capture', prompt: 'Kis type ka knowledge sabse pehle document karna chahiye?', type: 'textarea' },
  { id: 'M7', section: 'Operations', prompt: 'Konsi approvals ya decisions slow hain?', type: 'textarea' },
  { id: 'M8', section: 'Reporting', prompt: 'Daily, weekly, monthly kya track hona chahiye?', type: 'textarea' },
  { id: 'M9', section: 'Leadership', prompt: 'Kis person/role ki knowledge sabse critical hai?', type: 'textarea' },
  { id: 'M10', section: 'Leadership', prompt: 'Koi final note jo LD Brain ko yaad rakhna chahiye?', type: 'textarea' },
];

export const QUESTION_SETS: Record<InterviewRole, Question[]> = {
  nandu,
  md,
};
