import type { InterviewRole, Question } from '@/lib/types';

// Source: All_Questions_list/LD_Brain_MCQ_NanduBhai_Hindi.pdf
// 35 MCQ across 8 sections. Each question is presented to Nandu in either
// Latin Hinglish (default) or Devanagari (toggled via the script switch in
// the question header). Both versions carry the same content.
//
// `allowNotes: true` exposes a small "Notes / अन्य" textarea below the
// radio options so Nandu can write in something beyond A/B/C/D.
const nandu: Question[] = [
  {
    id: 'Q1',
    section: 'Sec 1: Machine Selection',
    sectionHi: 'भाग 1: मशीन चयन',
    prompt: 'Naya job aane par aap kaunsi machine chunte hain?',
    promptHi: 'नया जॉब आने पर आप कौन सी machine चुनते हैं?',
    type: 'radio',
    options: [
      'A. Jo machine us samay khali ho us par lagate hain',
      'B. Fabric ki chaudai dekhkar machine decide hoti hai',
      'C. Customer ki priority aur deadline dekhkar',
      'D. Job ki quality requirement dekhkar (premium job = achi machine)',
    ],
    optionsHi: [
      'A. जो machine उस समय खाली हो उस पर लगाते हैं',
      'B. Fabric की चौड़ाई देखकर machine decide होती है',
      'C. Customer की priority और deadline देखकर',
      'D. Job की quality requirement देखकर (premium job = अच्छी machine)',
    ],
    allowNotes: true,
    required: true,
  },
  {
    id: 'Q2',
    section: 'Sec 1: Machine Selection',
    sectionHi: 'भाग 1: मशीन चयन',
    prompt: 'Do urgent jobs ek hi machine chahte hon to aap kya karte hain?',
    promptHi: 'दो अर्जेंट jobs एक ही machine चाहते हों तो आप क्या करते हैं?',
    type: 'radio',
    options: [
      'A. Jo job pehle aaya wo pehle — first come first served',
      'B. Silk ke jobs ko hamesha priority dete hain',
      'C. Jiske zyada metres hon use pehle — bada order priority',
      'D. Raghav bhai se poochkar decide karte hain',
    ],
    optionsHi: [
      'A. जो job पहले आया वो पहले — first come first served',
      'B. Silk के jobs को हमेशा priority देते हैं',
      'C. जिसके ज़्यादा मीटर हों उसे पहले — बड़ा order priority',
      'D. राघव भाई से पूछकर decide करते हैं',
    ],
    allowNotes: true,
    required: true,
  },
  {
    id: 'Q3',
    section: 'Sec 1: Machine Selection',
    sectionHi: 'भाग 1: मशीन चयन',
    prompt: 'Naya job shuru karne se pehle machine par sabse pehle kya check karte hain?',
    promptHi: 'नया job शुरू करने से पहले machine पर सबसे पहले क्या check करते हैं?',
    type: 'radio',
    options: [
      'A. Ink levels — sabhi 4 colours (Black, Yellow, Magenta, Cyan)',
      'B. Paper roll — sahi width, sahi condition mein',
      'C. Machine ka temperature — pehle garam hone dete hain',
      'D. ICC profile — sahi profile load hai ya nahi',
    ],
    optionsHi: [
      'A. Ink levels — सभी 4 colours (Black, Yellow, Magenta, Cyan)',
      'B. Paper roll — सही width, सही condition में',
      'C. Machine का temperature — पहले गर्म होने देते हैं',
      'D. ICC profile — सही profile load है या नहीं',
    ],
    allowNotes: true,
    required: true,
  },
  {
    id: 'Q4',
    section: 'Sec 1: Machine Selection',
    sectionHi: 'भाग 1: मशीन चयन',
    prompt: 'Test swatch kab print karte hain?',
    promptHi: 'Test swatch कब print करते हैं?',
    type: 'radio',
    options: [
      'A. Har job se pehle — hamesha',
      'B. Sirf naye customer ka pehla job ho tab',
      'C. Naya design ya nayi fabric ho tab',
      'D. Jab colour match critical ho — bridal ya premium job',
    ],
    optionsHi: [
      'A. हर job से पहले — हमेशा',
      'B. सिर्फ नए customer का पहला job हो तब',
      'C. नया design या नई fabric हो तब',
      'D. जब colour match critical हो — bridal या premium job',
    ],
    allowNotes: true,
    required: true,
  },
  {
    id: 'Q5',
    section: 'Sec 1: Machine Selection',
    sectionHi: 'भाग 1: मशीन चयन',
    prompt: 'Agar koi MDO absent ho to aap kya karte hain?',
    promptHi: 'अगर कोई MDO absent हो तो आप क्या करते हैं?',
    type: 'radio',
    options: [
      'A. Doosre MDO ko us machine par shift karte hain',
      'B. Trained helper ko temporarily us machine par lagate hain',
      'C. Wo job agle din ke liye hold karte hain',
      'D. Pehle Raghav bhai ko inform karte hain, wo decide karein',
    ],
    optionsHi: [
      'A. दूसरे MDO को उस machine पर shift करते हैं',
      'B. Trained helper को temporarily उस machine पर लगाते हैं',
      'C. वो job अगले दिन के लिए hold करते हैं',
      'D. पहले राघव भाई को inform करते हैं, वो decide करें',
    ],
    allowNotes: true,
    required: true,
  },
  {
    id: 'Q6',
    section: 'Sec 1: Machine Selection',
    sectionHi: 'भाग 1: मशीन चयन',
    prompt: 'Shift khatm hone par agle shift ko kya zaroori batate hain?',
    promptHi: 'Shift खत्म होने पर अगले shift को क्या ज़रूरी बताते हैं?',
    type: 'radio',
    options: [
      'A. Kaunse jobs pending hain, kis machine par hain',
      'B. Agar machine mein koi problem aayi ho wo batate hain',
      'C. Ink aur paper ka stock status',
      'D. Teenon baatein batate hain — jobs + machine status + stock',
    ],
    optionsHi: [
      'A. कौन से jobs pending हैं, किस machine पर हैं',
      'B. अगर machine में कोई problem आई हो वो बताते हैं',
      'C. Ink और paper का stock status',
      'D. तीनों बातें बताते हैं — jobs + machine status + stock',
    ],
    allowNotes: true,
    required: true,
  },
  {
    id: 'Q7',
    section: 'Sec 2: Paper Selection',
    sectionHi: 'भाग 2: पेपर चयन',
    prompt: 'Nokia 58" fabric ke liye kaunsa paper width use karte hain?',
    promptHi: 'Nokia 58" fabric के लिए कौन सा paper width use करते हैं?',
    type: 'radio',
    options: [
      'A. 63" ya 64" paper',
      'B. 72" paper',
      'C. Fabric ki width ke barabar — 58" paper',
      'D. Fabric se thoda chaudaa paper — hamesha',
    ],
    optionsHi: [
      'A. 63" या 64" paper',
      'B. 72" paper',
      'C. Fabric की width के बराबर — 58" paper',
      'D. Fabric से थोड़ा चौड़ा paper — हमेशा',
    ],
    allowNotes: true,
    required: true,
  },
  {
    id: 'Q8',
    section: 'Sec 2: Paper Selection',
    sectionHi: 'भाग 2: पेपर चयन',
    prompt: 'Korean paper Chinese paper se behtar kyun hai?',
    promptHi: 'Korean paper Chinese paper से बेहतर क्यों है?',
    type: 'radio',
    options: [
      'A. Print quality behtar aati hai — design zyada sharp',
      'B. Colours zyada accurate transfer hote hain',
      'C. Machine mein smooth chalta hai, kam jam hoti hai',
      'D. Humidity mein bhi reliable rehta hai, Chinese jaldi kharab hota hai',
    ],
    optionsHi: [
      'A. Print quality बेहतर आती है — design ज़्यादा sharp',
      'B. Colours ज़्यादा accurate transfer होते हैं',
      'C. Machine में smooth चलता है, कम jam होती है',
      'D. Humidity में भी reliable रहता है, Chinese जल्दी ख़राब होता है',
    ],
    allowNotes: true,
    required: true,
  },
  {
    id: 'Q9',
    section: 'Sec 2: Paper Selection',
    sectionHi: 'भाग 2: पेपर चयन',
    prompt: 'Paper roll khatm hone wala ho aur job beech mein ho to kya karte hain?',
    promptHi: 'Paper roll खत्म होने वाला हो और job बीच में हो तो क्या करते हैं?',
    type: 'radio',
    options: [
      'A. Machine rokkar naya roll lagate hain, fir continue',
      'B. Us metre tak print karte hain fir roll badalte hain — banding check karte hain',
      'C. MDO ko khud decide karne dete hain',
      'D. Pehle plan karte hain — job shuru karne se pehle roll ka metre check karte hain',
    ],
    optionsHi: [
      'A. Machine रोककर नया roll लगाते हैं, फिर continue',
      'B. उस metre तक print करते हैं फिर roll बदलते हैं — banding check करते हैं',
      'C. MDO को खुद decide करने देते हैं',
      'D. पहले plan करते हैं — job शुरू करने से पहले roll का मीटर check करते हैं',
    ],
    allowNotes: true,
    required: true,
  },
  {
    id: 'Q10',
    section: 'Sec 2: Paper Selection',
    sectionHi: 'भाग 2: पेपर चयन',
    prompt: 'Humidity mein rakha paper roll kaise pehchante hain ki kharab ho gaya hai?',
    promptHi: 'Humidity में रखा paper roll कैसे पहचानते हैं कि ख़राब हो गया है?',
    type: 'radio',
    options: [
      'A. Paper ki edge curl ho jati hai',
      'B. Print karne par colour bleed hota hai',
      'C. Paper wrinkle pad jata hai machine mein',
      'D. Haath lagane par soft ya damp feel hota hai',
    ],
    optionsHi: [
      'A. Paper की edge curl हो जाती है',
      'B. Print करने पर colour bleed होता है',
      'C. Paper wrinkle पड़ जाता है machine में',
      'D. हाथ लगाने पर soft या damp feel होता है',
    ],
    allowNotes: true,
    required: true,
  },
  {
    id: 'Q11',
    section: 'Sec 3: Fusing Settings',
    sectionHi: 'भाग 3: फ्यूज़िंग सेटिंग्स',
    prompt: 'Nokia 58" ke liye fusing temperature kya rakhte hain?',
    promptHi: 'Nokia 58" के लिए fusing temperature क्या रखते हैं?',
    type: 'radio',
    options: [
      'A. 185–190°C',
      'B. 195–205°C',
      'C. 210–220°C',
      'D. 225–230°C',
    ],
    optionsHi: [
      'A. 185–190°C',
      'B. 195–205°C',
      'C. 210–220°C',
      'D. 225–230°C',
    ],
    allowNotes: true,
    help: 'Exact °C bhi likh sakte hain Notes mein',
    required: true,
  },
  {
    id: 'Q12',
    section: 'Sec 3: Fusing Settings',
    sectionHi: 'भाग 3: फ्यूज़िंग सेटिंग्स',
    prompt: 'Satin Slub ke liye Nokia 58" se compare karen to temperature?',
    promptHi: 'Satin Slub के लिए Nokia 58" से compare करें तो temperature?',
    type: 'radio',
    options: [
      'A. Nokia se zyada rakhte hain — Satin heavier hai',
      'B. Nokia se kam rakhte hain — Satin delicate hai',
      'C. Same temperature rakhte hain',
      'D. Temperature same, lekin speed kam karte hain Satin ke liye',
    ],
    optionsHi: [
      'A. Nokia से ज़्यादा रखते हैं — Satin heavier है',
      'B. Nokia से कम रखते हैं — Satin delicate है',
      'C. Same temperature रखते हैं',
      'D. Temperature same, लेकिन speed कम करते हैं Satin के लिए',
    ],
    allowNotes: true,
    required: true,
  },
  {
    id: 'Q13',
    section: 'Sec 3: Fusing Settings',
    sectionHi: 'भाग 3: फ्यूज़िंग सेटिंग्स',
    prompt: 'Heavy fabric (Scuba, Blackout, thick Georgette) par temperature?',
    promptHi: 'Heavy fabric (Scuba, Blackout, thick Georgette) पर temperature?',
    type: 'radio',
    options: [
      'A. Standard se 10–15°C zyada rakhte hain',
      'B. Standard se 20–25°C zyada rakhte hain',
      'C. Temperature same, speed kam karte hain',
      'D. Pehle ek chhota test karte hain, uske hisaab se adjust',
    ],
    optionsHi: [
      'A. Standard से 10–15°C ज़्यादा रखते हैं',
      'B. Standard से 20–25°C ज़्यादा रखते हैं',
      'C. Temperature same, speed कम करते हैं',
      'D. पहले एक छोटा test करते हैं, उसके हिसाब से adjust',
    ],
    allowNotes: true,
    required: true,
  },
  {
    id: 'Q14',
    section: 'Sec 3: Fusing Settings',
    sectionHi: 'भाग 3: फ्यूज़िंग सेटिंग्स',
    prompt: 'Under-fused fabric kaise pehchante hain?',
    promptHi: 'Under-fused fabric कैसे पहचानते हैं?',
    type: 'radio',
    options: [
      'A. Rang feeka lagta hai, theek se transfer nahi hua',
      'B. Haath se ragadne par rang nikalta hai',
      'C. Fabric ki surface par design thoda dhundla dikhta hai',
      'D. Kinaron par design kam aata hai, beech mein theek hai',
    ],
    optionsHi: [
      'A. रंग फीका लगता है, ठीक से transfer नहीं हुआ',
      'B. हाथ से रगड़ने पर रंग निकलता है',
      'C. Fabric की surface पर design थोड़ा धुंधला दिखता है',
      'D. किनारों पर design कम आता है, बीच में ठीक है',
    ],
    allowNotes: true,
    required: true,
  },
  {
    id: 'Q15',
    section: 'Sec 3: Fusing Settings',
    sectionHi: 'भाग 3: फ्यूज़िंग सेटिंग्स',
    prompt: 'Over-fused fabric kaise pehchante hain?',
    promptHi: 'Over-fused fabric कैसे पहचानते हैं?',
    type: 'radio',
    options: [
      'A. Fabric ki feel stiff ho jati hai, haath mein kada lagta hai',
      'B. Rang bahut gehre aate hain, original design se dark',
      'C. Fabric par shine badal jati hai',
      'D. Fabric ke edges burn ya darken ho jate hain',
    ],
    optionsHi: [
      'A. Fabric की feel stiff हो जाती है, हाथ में कड़ा लगता है',
      'B. रंग बहुत गहरे आते हैं, original design से dark',
      'C. Fabric पर shine बदल जाती है',
      'D. Fabric के edges burn या darken हो जाते हैं',
    ],
    allowNotes: true,
    required: true,
  },
  {
    id: 'Q16',
    section: 'Sec 4: Colour QC',
    sectionHi: 'भाग 4: कलर जाँच / क्वालिटी',
    prompt: 'Approved sample se colour compare karne ke liye kis roshni mein dekhte hain?',
    promptHi: 'Approved sample से colour compare करने के लिए किस रोशनी में देखते हैं?',
    type: 'radio',
    options: [
      'A. D65 light box mein',
      'B. Khidki ki natural daylight mein',
      'C. Factory ki LED light mein — jahan kaam hota hai wahin',
      'D. Do roshni mein dekhte hain — daylight aur artificial dono',
    ],
    optionsHi: [
      'A. D65 light box में',
      'B. खिड़की की natural daylight में',
      'C. Factory की LED light में — जहाँ काम होता है वहीं',
      'D. दो रोशनी में देखते हैं — daylight और artificial दोनों',
    ],
    allowNotes: true,
    required: true,
  },
  {
    id: 'Q17',
    section: 'Sec 4: Colour QC',
    sectionHi: 'भाग 4: कलर जाँच / क्वालिटी',
    prompt: 'Batch ka colour thoda alag lage to pehle kya check karte hain?',
    promptHi: 'Batch का colour थोड़ा अलग लगे तो पहले क्या check करते हैं?',
    type: 'radio',
    options: [
      'A. ICC profile — sahi profile load hai?',
      'B. Temperature — kam ya zyada to nahi?',
      'C. Ink levels — koi colour low to nahi?',
      'D. Paper batch — naya batch shuru hua to nahi?',
    ],
    optionsHi: [
      'A. ICC profile — सही profile load है?',
      'B. Temperature — कम या ज़्यादा तो नहीं?',
      'C. Ink levels — कोई colour low तो नहीं?',
      'D. Paper batch — नया batch शुरू हुआ तो नहीं?',
    ],
    allowNotes: true,
    required: true,
  },
  {
    id: 'Q18',
    section: 'Sec 4: Colour QC',
    sectionHi: 'भाग 4: कलर जाँच / क्वालिटी',
    prompt: 'Kitna colour difference acceptable hai? (Delta-E)',
    promptHi: 'कितना colour difference acceptable है? (Delta-E)',
    type: 'radio',
    options: [
      'A. Bilkul match chahiye — 0 to 2',
      'B. Thoda farq chalta hai — 0 to 3',
      'C. Practical tolerance — 0 to 5',
      'D. Customer ke hisaab se — koi strict nahi, feel dekhte hain',
    ],
    optionsHi: [
      'A. बिल्कुल match चाहिए — 0 to 2',
      'B. थोड़ा फर्क चलता है — 0 to 3',
      'C. Practical tolerance — 0 to 5',
      'D. Customer के हिसाब से — कोई strict नहीं, feel देखते हैं',
    ],
    allowNotes: true,
    required: true,
  },
  {
    id: 'Q19',
    section: 'Sec 4: Colour QC',
    sectionHi: 'भाग 4: कलर जाँच / क्वालिटी',
    prompt: 'Kaunsa defect dekhte hi job turant rok dete hain?',
    promptHi: 'कौन सा defect देखते ही job तुरंत रोक देते हैं?',
    type: 'radio',
    options: [
      'A. Banding — poore roll mein dhariyaan aa rahi hon',
      'B. Ghosting — double image dikh raha ho',
      'C. Colour poori tarah shift ho gaya ho — approved sample se bahut alag',
      'D. Design misalign ho gaya ho',
    ],
    optionsHi: [
      'A. Banding — पूरे roll में धारियाँ आ रही हों',
      'B. Ghosting — double image दिख रहा हो',
      'C. Colour पूरी तरह shift हो गया हो — approved sample से बहुत अलग',
      'D. Design misalign हो गया हो',
    ],
    allowNotes: true,
    required: true,
  },
  {
    id: 'Q20',
    section: 'Sec 4: Colour QC',
    sectionHi: 'भाग 4: कलर जाँच / क्वालिटी',
    prompt: 'Defective section ka kya karte hain — cut karte hain ya poora reject?',
    promptHi: 'Defective section का क्या करते हैं — cut करते हैं या पूरा reject?',
    type: 'radio',
    options: [
      'A. Defective hissa cut out karte hain, baaki deliver karte hain',
      'B. Customer ko batate hain, unki permission se deliver karte hain',
      'C. Reprint karte hain — customer ko wait karvate hain',
      'D. Depends on customer — kuch accept karte hain, kuch nahi',
    ],
    optionsHi: [
      'A. Defective हिस्सा cut out करते हैं, बाकी deliver करते हैं',
      'B. Customer को बताते हैं, उनकी permission से deliver करते हैं',
      'C. Reprint करते हैं — customer को wait करवाते हैं',
      'D. Depends on customer — कुछ accept करते हैं, कुछ नहीं',
    ],
    allowNotes: true,
    required: true,
  },
  {
    id: 'Q21',
    section: 'Sec 5: Defect Diagnosis',
    sectionHi: 'भाग 5: खराबी पहचान और सुधार',
    prompt: 'Banding (horizontal dhariyaan) aane par sabse pehle kya karte hain?',
    promptHi: 'Banding (horizontal धारियाँ) आने पर सबसे पहले क्या करते हैं?',
    type: 'radio',
    options: [
      'A. Nozzle check print lete hain — printhead check',
      'B. Paper change karte hain',
      'C. Machine band karke restart karte hain',
      'D. Printhead cleaning cycle chalate hain',
    ],
    optionsHi: [
      'A. Nozzle check print लेते हैं — printhead चेक',
      'B. Paper change करते हैं',
      'C. Machine बंद करके restart करते हैं',
      'D. Printhead cleaning cycle चलाते हैं',
    ],
    allowNotes: true,
    required: true,
  },
  {
    id: 'Q22',
    section: 'Sec 5: Defect Diagnosis',
    sectionHi: 'भाग 5: खराबी पहचान और सुधार',
    prompt: 'Ghosting (double image) ka sabse common kaaran kya hai?',
    promptHi: 'Ghosting (double image) का सबसे common कारण क्या है?',
    type: 'radio',
    options: [
      'A. Fabric machine mein shift ho jati hai — movement',
      'B. Temperature bahut zyada tha — fabric slip kiya',
      'C. Paper aur fabric theek se align nahi the',
      'D. Speed bahut tez thi',
    ],
    optionsHi: [
      'A. Fabric machine में shift हो जाती है — movement',
      'B. Temperature बहुत ज़्यादा था — fabric slip किया',
      'C. Paper और fabric ठीक से align नहीं थे',
      'D. Speed बहुत तेज़ थी',
    ],
    allowNotes: true,
    required: true,
  },
  {
    id: 'Q23',
    section: 'Sec 5: Defect Diagnosis',
    sectionHi: 'भाग 5: खराबी पहचान और सुधार',
    prompt: 'Ink spot / chheente ki problem kab zyada hoti hai?',
    promptHi: 'Ink spot / छींटे की problem कब ज़्यादा होती है?',
    type: 'radio',
    options: [
      'A. Ink level bahut kam ho jaaye tab',
      'B. Printhead purana ya block ho tab',
      'C. Humidity zyada ho tab',
      'D. Nayi ink batch shuru ki ho tab',
    ],
    optionsHi: [
      'A. Ink level बहुत कम हो जाए तब',
      'B. Printhead पुराना या block हो तब',
      'C. Humidity ज़्यादा हो तब',
      'D. नई ink batch शुरू की हो तब',
    ],
    allowNotes: true,
    required: true,
  },
  {
    id: 'Q24',
    section: 'Sec 5: Defect Diagnosis',
    sectionHi: 'भाग 5: खराबी पहचान और सुधार',
    prompt: 'Colour drift (poora batch ek direction mein shift ho) ka common kaaran?',
    promptHi: 'Colour drift (पूरा batch एक direction में shift हो) का common कारण?',
    type: 'radio',
    options: [
      'A. ICC profile galat load ho gayi',
      'B. Ink mein ek colour khatm hone lagi — balance bigda',
      'C. Paper batch badla tha — naya batch different behave kar raha',
      'D. Machine ka temperature drift ho gaya',
    ],
    optionsHi: [
      'A. ICC profile गलत load हो गई',
      'B. Ink में एक colour ख़त्म होने लगी — balance बिगड़ा',
      'C. Paper batch बदला था — नया batch different behave कर रहा',
      'D. Machine का temperature drift हो गया',
    ],
    allowNotes: true,
    required: true,
  },
  {
    id: 'Q25',
    section: 'Sec 6: Fabric Receiving',
    sectionHi: 'भाग 6: फैब्रिक रिसीविंग',
    prompt: 'Customer ka fabric aane par metres kaise check karte hain?',
    promptHi: 'Customer का fabric आने पर metres कैसे check करते हैं?',
    type: 'radio',
    options: [
      'A. Roll ko manually counter par naapte hain — har baar',
      'B. Visual estimate se andaaza lagate hain',
      'C. Weight se calculate karte hain',
      'D. Customer ke challan par trust, sirf spot check',
    ],
    optionsHi: [
      'A. Roll को manually counter पर नापते हैं — हर बार',
      'B. Visual estimate से अंदाज़ा लगाते हैं',
      'C. Weight से calculate करते हैं',
      'D. Customer के challan पर trust, सिर्फ spot check',
    ],
    allowNotes: true,
    required: true,
  },
  {
    id: 'Q26',
    section: 'Sec 6: Fabric Receiving',
    sectionHi: 'भाग 6: फैब्रिक रिसीविंग',
    prompt: 'Fabric customer ke challan se kam nikle to kya karte hain?',
    promptHi: 'Fabric customer के challan से कम निकले तो क्या करते हैं?',
    type: 'radio',
    options: [
      'A. Anand bhai ko batate hain — wo customer se baat karte hain',
      'B. Customer ko directly call/WhatsApp karte hain',
      'C. Discrepancy note banate hain aur job rokte hain customer confirm kare tab tak',
      'D. Kam metre ka job banakar aage badhte hain',
    ],
    optionsHi: [
      'A. Anand भाई को बताते हैं — वो customer से बात करते हैं',
      'B. Customer को directly call/WhatsApp करते हैं',
      'C. Discrepancy note बनाते हैं और job रोकते हैं customer confirm करे तब तक',
      'D. कम मीटर का job बनाकर आगे बढ़ते हैं',
    ],
    allowNotes: true,
    required: true,
  },
  {
    id: 'Q27',
    section: 'Sec 6: Fabric Receiving',
    sectionHi: 'भाग 6: फैब्रिक रिसीविंग',
    prompt: 'Damaged fabric aaye to kya karte hain?',
    promptHi: 'Damaged fabric आए तो क्या करते हैं?',
    type: 'radio',
    options: [
      'A. Wapas bhej dete hain',
      'B. Photo lete hain, customer ko batakar unki permission se accept',
      'C. Damaged hissa mark karte hain, baaki par print karte hain',
      'D. Anand/Raghav bhai se poochte hain, wo decide karein',
    ],
    optionsHi: [
      'A. वापस भेज देते हैं',
      'B. Photo लेते हैं, customer को बताकर उनकी permission से accept',
      'C. Damaged हिस्सा mark करते हैं, बाकी पर print करते हैं',
      'D. Anand/Raghav भाई से पूछते हैं, वो decide करें',
    ],
    allowNotes: true,
    required: true,
  },
  {
    id: 'Q28',
    section: 'Sec 6: Fabric Receiving',
    sectionHi: 'भाग 6: फैब्रिक रिसीविंग',
    prompt: 'Fabric kitne din store mein rahe to customer ko remind karte hain ki order de?',
    promptHi: 'Fabric कितने दिन store में रहे तो customer को remind करते हैं कि order दे?',
    type: 'radio',
    options: [
      'A. 15 din',
      'B. 30 din',
      'C. 45 din',
      'D. Jab tak customer order na de, store mein rakhte hain — hamari zimmedari',
    ],
    optionsHi: [
      'A. 15 दिन',
      'B. 30 दिन',
      'C. 45 दिन',
      'D. जब तक customer order न दे, store में रखते हैं — हमारी ज़िम्मेदारी',
    ],
    allowNotes: true,
    required: true,
  },
  {
    id: 'Q29',
    section: 'Sec 7: Dispatch + Packaging',
    sectionHi: 'भाग 7: डिस्पैच और पैकेजिंग',
    prompt: 'Finished fabric roll ki packaging standard kya hai?',
    promptHi: 'Finished fabric roll की packaging standard क्या है?',
    type: 'radio',
    options: [
      'A. Polybag mein lapetkar, fir brown paper',
      'B. Sirf polybag — fabric ke upar',
      'C. Customer ke hisaab se alag-alag packaging',
      'D. Hard core mein roll karke polybag',
    ],
    optionsHi: [
      'A. Polybag में लपेटकर, फिर brown paper',
      'B. सिर्फ polybag — fabric के ऊपर',
      'C. Customer के हिसाब से अलग-अलग packaging',
      'D. Hard core में roll करके polybag',
    ],
    allowNotes: true,
    required: true,
  },
  {
    id: 'Q30',
    section: 'Sec 7: Dispatch + Packaging',
    sectionHi: 'भाग 7: डिस्पैच और पैकेजिंग',
    prompt: 'Roll label par kya-kya likhte hain?',
    promptHi: 'Roll label पर क्या-क्या लिखते हैं?',
    type: 'radio',
    options: [
      'A. Customer name + Job number + metres',
      'B. Customer name + design name + width + metres',
      'C. Challan number + roll number + metres',
      'D. Sab — customer, design, width, metres, challan number',
    ],
    optionsHi: [
      'A. Customer name + Job number + metres',
      'B. Customer name + design name + width + metres',
      'C. Challan number + roll number + metres',
      'D. सब — customer, design, width, metres, challan number',
    ],
    allowNotes: true,
    required: true,
  },
  {
    id: 'Q31',
    section: 'Sec 7: Dispatch + Packaging',
    sectionHi: 'भाग 7: डिस्पैच और पैकेजिंग',
    prompt: 'Dispatch se pehle final check mein kya verify karte hain?',
    promptHi: 'Dispatch से पहले final check में क्या verify करते हैं?',
    type: 'radio',
    options: [
      'A. Total metres match karta hai order se',
      'B. Roll labels sahi hain',
      'C. Challan ready hai',
      'D. Teenon — metres + labels + challan',
    ],
    optionsHi: [
      'A. Total metres match करता है order से',
      'B. Roll labels सही हैं',
      'C. Challan ready है',
      'D. तीनों — metres + labels + challan',
    ],
    allowNotes: true,
    required: true,
  },
  {
    id: 'Q32',
    section: 'Sec 7: Dispatch + Packaging',
    sectionHi: 'भाग 7: डिस्पैच और पैकेजिंग',
    prompt: 'Job 980 metres bani, order 1000 metres ka tha — kya karte hain?',
    promptHi: 'Job 980 metres बनी, order 1000 metres का था — क्या करते हैं?',
    type: 'radio',
    options: [
      'A. 980 dispatch karte hain, customer ko batate hain aur balance baad mein dete hain',
      'B. Job rokte hain — 1000 poora ho jaye tab dispatch',
      'C. 20 metres reprint karke saath bhejte hain',
      'D. Raghav bhai se poochte hain — unka decision',
    ],
    optionsHi: [
      'A. 980 dispatch करते हैं, customer को बताते हैं और balance बाद में देते हैं',
      'B. Job रोकते हैं — 1000 पूरा हो जाए तब dispatch',
      'C. 20 metres reprint करके साथ भेजते हैं',
      'D. Raghav भाई से पूछते हैं — उनका decision',
    ],
    allowNotes: true,
    required: true,
  },
  {
    id: 'Q33',
    section: 'Sec 8: Vendors + Stock',
    sectionHi: 'भाग 8: वेंडर और सप्लाई',
    prompt: 'Korean paper urgently chahiye ho 24 ghante mein — kise call karte hain?',
    promptHi: 'Korean paper urgently चाहिए हो 24 घंटे में — किसे call करते हैं?',
    type: 'radio',
    options: [
      'A. Regular supplier ko directly — mere paas unka number hai',
      'B. Anand bhai ko bolte hain, wo arrange karte hain',
      'C. Raghav bhai ko bolte hain',
      'D. Mahesh/Aditya ko bolte hain',
    ],
    optionsHi: [
      'A. Regular supplier को directly — मेरे पास उनका number है',
      'B. Anand भाई को बोलते हैं, वो arrange करते हैं',
      'C. Raghav भाई को बोलते हैं',
      'D. Mahesh/Aditya को बोलते हैं',
    ],
    allowNotes: true,
    help: 'Supplier ka naam/number Notes mein',
    required: true,
  },
  {
    id: 'Q34',
    section: 'Sec 8: Vendors + Stock',
    sectionHi: 'भाग 8: वेंडर और सप्लाई',
    prompt: 'Ink order kitne pehle de dete hain?',
    promptHi: 'Ink order कितने पहले दे देते हैं?',
    type: 'radio',
    options: [
      'A. 2–3 din pehle — jab low ho tab',
      'B. 5–7 din pehle',
      'C. 10–15 din pehle',
      'D. 30+ din ka buffer rakhte hain — kabhi kam nahi hone dete',
    ],
    optionsHi: [
      'A. 2–3 दिन पहले — जब low हो तब',
      'B. 5–7 दिन पहले',
      'C. 10–15 दिन पहले',
      'D. 30+ दिन का buffer रखते हैं — कभी कम नहीं होने देते',
    ],
    allowNotes: true,
    required: true,
  },
  {
    id: 'Q35',
    section: 'Sec 8: Vendors + Stock',
    sectionHi: 'भाग 8: वेंडर और सप्लाई',
    prompt: 'Paper stock kitna minimum rakhte hain factory mein?',
    promptHi: 'Paper stock कितना minimum रखते हैं factory में?',
    type: 'radio',
    options: [
      'A. 2–3 din ka — just-in-time',
      'B. 1 hafte ka',
      'C. 15 din ka',
      'D. 1 mahine ka — isse kam ho to order de dete hain',
    ],
    optionsHi: [
      'A. 2–3 दिन का — just-in-time',
      'B. 1 हफ्ते का',
      'C. 15 दिन का',
      'D. 1 महीने का — इससे कम हो तो order दे देते हैं',
    ],
    allowNotes: true,
    required: true,
  },
];

const md: Question[] = [
  { id: 'M1', section: 'Management Vision', prompt: 'Aaj ke liye top 3 business priorities kya hain?', type: 'textarea' },
  { id: 'M2', section: 'Management Vision', prompt: 'Aap kis cheez par bilkul compromise nahi karna chahte?', type: 'textarea' },
  { id: 'M3', section: 'Decision Rules', prompt: 'Speed, quality, cost mein conflict aaye to decision rule kya hota hai?', type: 'radio', options: ['Speed first', 'Quality first', 'Cost first', 'Case by case'] },
  { id: 'M4', section: 'Growth', prompt: 'Agale 90 din mein sabse bada growth goal kya hai?', type: 'textarea' },
  { id: 'M5', section: 'Bottlenecks', prompt: 'Aaj growth ko sabse zyada kya block kar raha hai?', type: 'textarea' },
  { id: 'M6', section: 'Knowledge Capture', prompt: 'Kis type ka knowledge sabse pehle document karna chahiye?', type: 'textarea' },
  { id: 'M7', section: 'Operations', prompt: 'Konsi approvals ya decisions slow hain?', type: 'textarea' },
  { id: 'M8', section: 'Reporting', prompt: 'Daily, weekly, monthly kya track hona chahiye?', type: 'textarea' },
  { id: 'M9', section: 'Leadership', prompt: 'Kis person/role ki knowledge sabse critical hai?', type: 'textarea' },
  { id: 'M10', section: 'Leadership', prompt: 'Koi final note jo LD Brain ko yaad rakhna chahiye?', type: 'textarea' },
];

export const QUESTION_SETS: Record<InterviewRole, Question[]> = {
  nandu,
  md,
};
